---

- hosts: all
  become: true 
  tasks:
    
  - name: update reposotory
    apt:
      update_cache: yes
 
  - name: install apache2 package
    apt:	
      name: apache2      
      state: absent
  
  - name: add php support or apache
    apt:
      name: libapache2-mod-php
      state: absent

